from django.urls import path

from main.views import (
    create_experience,
    create_project,
    create_project_ajax,
    delete_discography,
    delete_experience,
    delete_project,
    get_experiences_json,
    get_projects_json,
    show_edit,
    show_experience,
    show_discography,
    show_main,
    show_projects,
    toggle_star,
    toggle_experience_star,
    toggle_discography_star,
    update_discography,
    update_experience,
    update_project,
    register,
    login_user,
    logout_user,
)

app_name = "main"

urlpatterns = [
    path("", show_main, name="show_main"),
    path("edit/", show_edit, name="show_edit"),
    path("experience/", show_experience, name="show_experience"),
    path("experience/add/", create_experience, name="create_experience"),
    path("experience/<uuid:experience_id>/update/", update_experience, name="update_experience"),
    path("experience/<uuid:experience_id>/delete/", delete_experience, name="delete_experience"),
    path("experience/<uuid:experience_id>/star/", toggle_experience_star, name="toggle_experience_star"),
    path("api/experiences", get_experiences_json, name="get_experiences_json"),
    path("api/experiences/", get_experiences_json),
    path("projects/", show_projects, name="show_projects"),
    path("discography/", show_discography, name="show_discography"),
    path("projects/add/", create_project, name="create_project"),
    path("projects/add-ajax/", create_project_ajax, name="create_project_ajax"),
    path("projects/<int:project_id>/update/", update_project, name="update_project"),
    path("projects/<int:project_id>/delete/", delete_project, name="delete_project"),
    path("projects/<int:project_id>/star/", toggle_star, name="toggle_star"),
    path("discography/<int:entry_id>/update/", update_discography, name="update_discography"),
    path("discography/<int:entry_id>/delete/", delete_discography, name="delete_discography"),
    path("discography/<int:entry_id>/star/", toggle_discography_star, name="toggle_discography_star"),
    path("api/projects", get_projects_json, name="get_projects_json"),
    path("api/projects/", get_projects_json),
    path("register/", register, name="register"),
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
]
