# Generated by Django 6.0.8 on 2026-09-14 02:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscographyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_type', models.CharField(max_length=100)),
                ('context', models.CharField(max_length=255)),
                ('audio_filename', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Use an existing .mp3 filename from static/audio; paths are not allowed.', regex='^[A-Za-z0-9][A-Za-z0-9_.-]*\\.mp3$')])),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'discography entries',
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('period', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=255)),
                ('link_label', models.CharField(max_length=100)),
                ('link_url', models.URLField()),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='DiscographyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main.discographyentry')),
            ],
            options={
                'ordering': ('order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='DiscographyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='main.discographyentry')),
            ],
            options={
                'ordering': ('order', 'label'),
                'constraints': [models.UniqueConstraint(fields=('entry', 'label'), name='unique_discography_role')],
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='main.project')),
            ],
            options={
                'ordering': ('order', 'label'),
                'constraints': [models.UniqueConstraint(fields=('project', 'label'), name='unique_project_tag')],
            },
        ),
    ]
