# Generated by Django 6.0.8 on 2026-09-14

from django.db import migrations, models


def copy_to_parent_models(apps, schema_editor):
    Project = apps.get_model("main", "Project")
    ProjectTag = apps.get_model("main", "ProjectTag")
    DiscographyEntry = apps.get_model("main", "DiscographyEntry")
    DiscographyRole = apps.get_model("main", "DiscographyRole")
    DiscographyLink = apps.get_model("main", "DiscographyLink")

    for project in Project.objects.all():
        project.project_tags = list(
            ProjectTag.objects.filter(project=project).order_by("order", "label").values_list("label", flat=True)
        )
        project.save(update_fields=["project_tags"])

    for entry in DiscographyEntry.objects.all():
        entry.role_labels = list(
            DiscographyRole.objects.filter(entry=entry).order_by("order", "label").values_list("label", flat=True)
        )
        entry.external_links = list(
            DiscographyLink.objects.filter(entry=entry).order_by("order", "label").values("label", "url")
        )
        entry.save(update_fields=["role_labels", "external_links"])


def copy_to_child_models(apps, schema_editor):
    Project = apps.get_model("main", "Project")
    ProjectTag = apps.get_model("main", "ProjectTag")
    DiscographyEntry = apps.get_model("main", "DiscographyEntry")
    DiscographyRole = apps.get_model("main", "DiscographyRole")
    DiscographyLink = apps.get_model("main", "DiscographyLink")

    for project in Project.objects.all():
        for order, label in enumerate(project.project_tags, start=1):
            ProjectTag.objects.get_or_create(project=project, label=label, defaults={"order": order})

    for entry in DiscographyEntry.objects.all():
        for order, label in enumerate(entry.role_labels, start=1):
            DiscographyRole.objects.get_or_create(entry=entry, label=label, defaults={"order": order})
        for order, link in enumerate(entry.external_links, start=1):
            DiscographyLink.objects.get_or_create(
                entry=entry,
                label=link["label"],
                defaults={"url": link["url"], "order": order},
            )


class Migration(migrations.Migration):
    dependencies = [("main", "0003_seed_projects_and_discography")]

    operations = [
        migrations.AddField(
            model_name="discographyentry",
            name="external_links",
            field=models.JSONField(blank=True, default=list, help_text='Example: [{"label": "Listen", "url": "https://example.com"}]'),
        ),
        migrations.AddField(
            model_name="discographyentry",
            name="role_labels",
            field=models.JSONField(blank=True, default=list, help_text='Example: ["Writer", "Composer"]'),
        ),
        migrations.AddField(
            model_name="project",
            name="project_tags",
            field=models.JSONField(blank=True, default=list, help_text='Example: ["Django", "Python"]'),
        ),
        migrations.RunPython(copy_to_parent_models, copy_to_child_models),
        migrations.RemoveField(model_name="discographylink", name="entry"),
        migrations.RemoveConstraint(model_name="discographyrole", name="unique_discography_role"),
        migrations.RemoveConstraint(model_name="projecttag", name="unique_project_tag"),
        migrations.DeleteModel(name="DiscographyLink"),
        migrations.RemoveField(model_name="projecttag", name="project"),
        migrations.DeleteModel(name="DiscographyRole"),
        migrations.DeleteModel(name="ProjectTag"),
        migrations.RenameField(model_name="project", old_name="project_tags", new_name="tags"),
        migrations.RenameField(model_name="discographyentry", old_name="role_labels", new_name="roles"),
        migrations.RenameField(model_name="discographyentry", old_name="external_links", new_name="links"),
    ]
